export LANG='en_US.UTF-8'
export EDITOR=vim
export VISUAL="$EDITOR"

export NIX_CONFIG_PATH=~/.config/nix

. ~/.alias

eval "$(oh-my-posh init zsh --config '~/oh-my-posh.omp.json')"
eval "$(zoxide init zsh --cmd cd)"

source <(COMPLETE=zsh jj)
eval "$(gh completion -s zsh)"

if [[ $PWD == */.delta/worktrees/* ]]; then
  export GH_CONFIG_DIR="$HOME/.config/delta"
  if [[ -r "$HOME/.config/delta/bot-token" ]]; then
    export GH_TOKEN="$(<"$HOME/.config/delta/bot-token")"
  fi
fi
