export LANG='en_US.UTF-8'
export EDITOR=vim
export VISUAL="$EDITOR"

export NIX_CONFIG_PATH=~/.config/nix

. ~/.alias

eval "$(oh-my-posh init zsh --config '~/oh-my-posh.omp.json')"
eval "$(zoxide init zsh --cmd cd)"
